name: example-mongodb
members: 3
version: "4.4.6"
persistent: true
adminPassword: change-me
user:
  name: admin
  db: admin
  passwordSecretRef: mongo-admin-password
  roles:
    - name: clusterAdmin
      db: admin
    - name: userAdminAnyDatabase
      db: admin
    - name: dbAdminAnyDatabase
      db: admin
    - name: readWriteAnyDatabase
      db: admin
scramCredentialsSecretName: ""
connectionStringSecretName: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

dataVolumeStorage: "10Gi"
logVolumeStorage: "2Gi"

additionalMongodConfig: {}
additionalConnectionStringConfig: {}
containersAdditionalConfig: {}
