---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mongodb.fullname" . }}-database-rbac
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mongodb.fullname" . }}-database
  apiGroup: rbac.authorization.k8s.io
