{{- $fullName := include "mongodb.fullname" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-{{ .Values.user.passwordSecretRef }}
  labels:
  {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.adminPassword }}

{{ if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "mongodb.fullname" . }}-{{ .Values.metrics.passwordSecretRef }}"
type: Opaque
stringData:
  password: {{ .Values.metrics.password }}
{{- end }}


{{- if and (.Values.backup.enabled) (.Values.backup.cronjob.container_secret_env) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-backup-secrets
type: Opaque
stringData:
{{- range .Values.backup.cronjob.container_secret_env }}
  {{ .secret_key }}: {{ .value }}
{{- end }}
{{- end }}

{{- if and (.Values.backup.enabled) (.Values.backup.cronjob.imagePullSecrets) }}
{{- range .Values.backup.cronjob.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ $fullName }}-{{ .name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
