---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-{{ .Values.user.passwordSecretRef }}
  labels:
  {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.adminPassword }}
