---
name: Lint

on:
  push:
    branches: [main]
    paths:
      - 'templates/**'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [main]
    paths:
      - 'templates/**'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run Linter
        run: devenv shell task lint
